version: 2

models:
  - name: stg_production_database__brands
    description: "This model contains information about brands"
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand."
        tests:
            - unique
            - not_null

  - name: stg_production_database__categories
    description: "This model contains information about product categories"
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each prodcut category."
        tests:
            - unique
            - not_null

  - name: stg_production_database__products
    description: "This model contains information about products"
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null
      - name: category_id
        description: "Foreign key linking the brand products to the category."
        tests:
          - relationships:
              name: category_id_id_foreign_key_in_stg_production_database__products
              to: ref('stg_production_database__categories')
              field: category_id
      - name: brand_id
        description: "Foreign key linking the brand products to the brand table."
        tests:
          - relationships:
              name: brand_id_id_foreign_key_in_stg_production_database__brands
              to: ref('stg_production_database__brands')
              field: brand_id
  
  - name: stg_production_database__stocks
    description: "This model contains information about stocks of products by store"
    columns:
      - name: store_product_id
        description: "Primary key, unique identifier for each store product: generated by concatenating store_id and product_id."
        tests:
            - unique
            - not_null
      - name: store_id
        description: "Foreign key linking stocks to the corresponding store."
        tests:
          - relationships:
              name: store_id_id_foreign_key_in_stg_sales_database__stores
              to: ref('stg_sales_database__stores')
              field: store_id
      - name: product_id
        description: "Foreign key linking stocks to the corresponding product."
        tests:
          - relationships:
              name: product_id_id_foreign_key_in_stg_sales_database__products
              to: ref('stg_production_database__products')
              field: product_id